# Generated by Django 3.1.1 on 2020-11-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='users',
            new_name='user',
        ),
    ]
